services:
  - type: web
    name: candy-dash
    runtime: python
    region: virginia
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 'app:create_app()'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: candy-dash-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: candy-dash-db
    databaseName: candy_dash
    user: candy_user
    region: virginia