services:
  - type: web
    name: candy-dash
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app()
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: DATABASE_URL
        fromDatabase:
          name: candy-dash-db
          property: connectionString

databases:
  - name: candy-dash-db
    databaseName: candy_dash
    user: candy_user
